### ISSUE TITLE
Clear build error messages

### ISSUE THREAD

**Issue by pe3** [pe3/react-boilerplate#11]
# todo
- [ ] paste in examples (with causes) of good error messages
- [ ] what is the technical setups have produced good messages
- [ ] paste in some examples (with causes) of bad error messages
  - [ ] reproduce checkbox console error
- [ ] what is the technical setup which causes bad messages
  - [ ] how is [react-to-html-webpack-plugin](https://github.com/markdalgleish/react-to-html-webpack-plugin)
- [ ] update readme
