### ISSUE TITLE
Effective debugging

### ISSUE THREAD

**Issue by pe3** [pe3/react-boilerplate#12]
# todo
- [ ] update build system to tolerate `console.log`
- [ ] evaluate chrome dev tools (breakpoints)
  - [features](http://elijahmanor.com/7-chrome-tips-developers-designers-may-not-know/)
  - [read](https://developer.chrome.com/devtools/docs/javascript-debugging)
  - [set breakpoint in code](http://stackoverflow.com/questions/10050465/set-a-javascript-breakpoint-in-code-in-chrome)
  - [in window](http://stackoverflow.com/questions/5156388/how-to-set-breakpoints-in-inline-javascript-in-google-chrome)
  - [wathc](http://googledevelopers.blogspot.fi/2014/01/discover-devtools-course-updated-and.html)
- [ ] how to debug webpack?
- [ ] test at least store code [node-inspector](https://github.com/node-inspector/node-inspector) with chrome devtools
- [ ] is [bunyan](https://github.com/trentm/node-bunyan) any good
